name: Online Maker

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check-bots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Bot Checker
        env:
          CHAT_ID: ${{ secrets.CHAT_ID }}
          OWNER_ID: ${{ secrets.OWNER_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKENS }}
        run: python bot.py
